version: '3.8'

services:
  one-frame:
    image: paidyinc/one-frame:latest
    container_name: one-frame-service
    ports:
        - "8080:8080"

  forex-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forex-proxy-service
    depends_on:
      - one-frame
#    environment:
#      - ONE_FRAME_BASE_URL=http://one-frame:8080
#      - TOKEN=your_api_token_here
    ports:
      - "9000:9000"
    command: ["java", "-jar", "/app/forex-proxy.jar"]
#    environment:
#      - CONFIG_FILE=/app/docker-application.conf
    volumes:
        - ./src/main/resources/docker-application.conf:/app/docker-application.conf